name: 'Terraform-Destroy'

on:
    workflow_dispatch: 

permissions: 
    contents: read

jobs:
    terraform:
        name: 'Terraform-Destroy'
        runs-on: ubuntu-latest
        environment: dev

        defaults:
            run:
                shell: bash
        
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          id: init
          run: terraform init
          env: GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Destroy
          id: destroy
          run: terraform destroy -auto-approve
          env: GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
